

services:
  database:
    image: mysql:8.0
    container_name: live_on_tab_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: live_on_tab
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: live_on_tab_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/live_on_tab
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: apppassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
